### DISCUSSION TITLE
PR Drafter & Release Note

### DISCUSSION THREAD

**Discussion by seonyae-park** [seonyae-park/hello-charlie#19] [General]
**_Release Drafter_**
- https://github.com/release-drafter/release-drafter
- 타겟 브랜치를 향하는 PR 을 기준으로 변경사항을 자동으로 생성해주는 도구
  - 이 변경사항을 draft release 의 내용으로 만들어 준다.
- 또한, PR 을 생성하면 자동으로 Label 을 달아준다.
  - 브랜치명이나 PR 타이틀에 특정 단어가 들어가면 라벨링으로 인식하고 지정

> 첫 draft release 의 모습

![](https://github.com/user-attachments/assets/e4e95b6a-8d40-4a2d-a39d-5038927fe011)

**_details_**
- PR 을 기준으로 release-drafter 의 작업 수행

```
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]    // `main` 브랜치에서 시작된 PR 이 생성되거나 변경되었을 때 트리거
``` 

- config 파일을 정의하여 상세옵션 설정
  - `name-template`, `tag-template` 
 
   ```
   name-template: "v$RESOLVED_VERSION 🌈"    // draft-release 의 타이틀
   tag-template: "v$RESOLVED_VERSION"              // draft-release 의 태그명
   ```
   - `categories`
   
   ```
   categories:
   - title: "🚀 Features"           // `feature` 라벨이 붙은 PR 들은 `🚀 Features` 타이틀 아래에 리스트업
    labels:
      - "feature"
   ```
   - `autolabeler`: PR 의 타이틀이나 브랜치명을 보고 자동으로 GitHub 라벨을 할당해주는 역할
   
   ```
   autolabeler:
     - label: "feature"          // 브랜치 경로에 `feat/` 이 있거나 타이틀 명에 `feat:` 이 있으면 "feature" 라벨로 지정
       branch:
         - '/feat\/.+/'
       title:
         - "/feat:/i"
   ```
   - changes 내용에 관한 옵션
   
   ```
   change-template: "- $TITLE @$AUTHOR (#$NUMBER)" 
   change-title-escapes: '\<*_&'     // 마크다운 문법에서 필터링 될 수 있을 기호 중, ${TITLE} 에서 제외되고 싶지 않은 경우 지정
   ```
   ![image](https://github.com/user-attachments/assets/b3436453-cb7f-43a9-8a79-696b0093ed83)
   - `version-resolver`: PR 중 major/minor/patch 라벨이 있으면, draft-release 의 ${RESOLVED_VERSION} 의 버저닝 방식에 반영 
   ```
   version-resolver:
     major:
       labels:
         - "major"
     minor:
       labels:
         - "minor"
     patch:
       labels:
         - "patch"
     default: patch    // 이런 라벨이 하나도 없으면 기본적으로 patch 가 올라감
   ```
